/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ARDUTEST_VERSION_H
#define ARDUTEST_VERSION_H

#define ARDUTEST_VERSION_MAJOR 0
#define ARDUTEST_VERSION_MINOR 2
#define ARDUTEST_VERSION_PATCH 0
#define ARDUTEST_VERSION_STR "0.2.0"

#endif // ARDUTEST_VERSION_H
